In [47]:
import numpy as np
import pandas as pd
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [48]:
from sklearn.datasets import load_iris
from sklearn.datasets import load_digits

In [49]:
iris=load_iris()
dir(iris)

['DESCR',
 'data',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [50]:
from sklearn.model_selection import train_test_split

In [51]:
X_train,X_test,y_train,y_test=train_test_split(iris.data,iris.target,test_size=0.3)

In [52]:
def train_model(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)
    

In [53]:
train_model(LogisticRegression(),X_train,X_test,y_train,y_test)

0.9555555555555556

In [54]:
from sklearn.model_selection import StratifiedKFold

In [55]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)


In [56]:
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=3)

In [61]:
l_score=[]
s_score=[]
t_score=[]
for train_index,test_index in kf.split(iris.data):
    X_train,X_test,y_train,y_test=iris.data[train_index],iris.data[train_index],iris.target[train_index],iris.target[train_index]
    l_score.append(train_model(LogisticRegression(),X_train,X_test,y_train,y_test))
    s_score.append(train_model(SVC(),X_train,X_test,y_train,y_test))
    t_score.append(train_model(RandomForestClassifier(),X_train,X_test,y_train,y_test))
    

In [62]:
l_score


[1.0, 1.0, 1.0]

In [59]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [63]:
s_score


[1.0, 1.0, 1.0]

In [64]:
t_score

[1.0, 1.0, 1.0]

In [65]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(),iris.data,iris.target)


C:\Users\Yoga\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [67]:
cross_val_score(SVC(),iris.data,iris.target)

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [70]:
cross_val_score(RandomForestClassifier(n_estimators=40),iris.data,iris.target)

array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ])